name: GitHub Contribution Snake

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user: nayvti380
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Commit and push the snake animation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update contribution snake"
          branch: main
          file_pattern: "dist/github-contribution-grid-snake.svg"
